# 플러그인 문의는 아래 디스코드로 연락해주세요!
# 제작자 디스코드 : 조상준#0897
##########################################################################################

## 마을 설정 ##

# 마을에 사용되는 재화는 다이아몬드이며, 우측의 숫자는 필요한 다이아몬드의 개수를 의미합니다!
마을 생성 비용 : 5
마을 2단계 비용 : 20
마을 3단계 비용 : 100
마을 4단계 비용 : 300


## 마을 생성 제한 설정 ##
## 우측의 숫자는 블럭의 수를 의미합니다.
## 한 마을의 최대 크기는 301 x 301 입니다.
## 거리 측정은 마을 중앙의 좌표 기준입니다.
스폰과의 최소 거리 : 300
마을과의 최소 거리 : 500